# Generated by Django 5.2.17 on 2026-08-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('az', 'Azərbaycan'), ('ar', 'Ərəb'), ('en', 'İngilis')], default='az', max_length=8)),
                ('cover_tone', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('manual', 'Manual'), ('import', 'Import'), ('api', 'API')], default='api', max_length=20)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.book')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('book', 'public_id')},
            },
        ),
    ]
