# Generated by Django 5.2.17 on 2026-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kanal adı')),
                ('url', models.URLField(max_length=500, verbose_name='Kanal linki')),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video kanal',
                'verbose_name_plural': 'Video kanallar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
