# Generated by Django 5.2.17 on 2026-08-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videochannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Silsilə adı')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.videochannel', verbose_name='Kanal')),
            ],
            options={
                'verbose_name': 'Silsilə dərs',
                'verbose_name_plural': 'Silsilə dərslər',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Dərs adı')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='Video linki')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.videoseries', verbose_name='Silsilə')),
            ],
            options={
                'verbose_name': 'Dərs',
                'verbose_name_plural': 'Dərslər',
                'ordering': ['order', 'id'],
            },
        ),
    ]
