# Generated by Django 5.2.17 on 2026-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_videoseries_videolesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Dərs (istəyə bağlı)', 'verbose_name_plural': 'Dərslər (istəyə bağlı)'},
        ),
        migrations.AddField(
            model_name='videoseries',
            name='playlist_url',
            field=models.URLField(blank=True, default='', help_text='Məs: https://www.youtube.com/playlist?list=... və ya https://www.youtube.com/@Kanal/playlists — dərsləri tək-tək əlavə etmək lazım deyil.', max_length=500, verbose_name='Playlist / playlists linki'),
        ),
        migrations.AlterField(
            model_name='videochannel',
            name='url',
            field=models.URLField(help_text='Məs: https://www.youtube.com/@Abu_Zeyd_Habibli/playlists', max_length=500, verbose_name='Kanal / playlists linki'),
        ),
    ]
