# Generated by Django 5.2.17 on 2026-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_videolesson_options_videoseries_playlist_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Dərs', 'verbose_name_plural': 'Dərslər'},
        ),
        migrations.AddField(
            model_name='videolesson',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Endirilmiş audio — onlayn dinləmə və telefona yükləmə', null=True, upload_to='audio/%Y/%m/', verbose_name='Səs faylı'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='videochannel',
            name='url',
            field=models.URLField(help_text='Məs: https://www.youtube.com/@Abu_Zeyd_Habibli/playlists — saxlayanda bütün playlistlər silsilə kimi yüklənir.', max_length=500, verbose_name='Kanal / playlists linki'),
        ),
    ]
