# Generated by Django 5.2.17 on 2026-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_videolesson_options_videolesson_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('contact', models.CharField(blank=True, default='', help_text='E-poçt və ya telefon (istəyə bağlı)', max_length=200, verbose_name='Əlaqə')),
                ('category', models.CharField(choices=[('question', 'Sual'), ('problem', 'Problem'), ('suggestion', 'Təklif'), ('other', 'Digər')], default='question', max_length=20, verbose_name='Kateqoriya')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dəstək mesajı',
                'verbose_name_plural': 'Dəstək mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
