# Generated by Django 5.2.17 on 2026-08-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
