# Generated by Django 5.2.17 on 2026-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chapter_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('teacher_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Müəllim')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Qısa təsvir')),
                ('telegram_url', models.URLField(help_text='Qrup, kanal və ya canlı yayım linki (t.me/...)', max_length=500, verbose_name='Telegram linki')),
                ('starts_at', models.DateTimeField(verbose_name='Başlanğıc')),
                ('ends_at', models.DateTimeField(verbose_name='Bitmə')),
                ('force_status', models.CharField(blank=True, choices=[('', 'Avtomatik (vaxta görə)'), ('live', 'Məcburi canlı'), ('ended', 'Məcburi bitib')], default='', max_length=10, verbose_name='Status override')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram canlı dərs',
                'verbose_name_plural': 'Telegram canlı dərslər',
                'ordering': ['-starts_at', 'order', 'id'],
            },
        ),
    ]
