# Generated by Django 5.2.3 on 2026-09-18 19:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_meal_note_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('text', 'Mətn'), ('pdf', 'PDF')], default='text', max_length=8),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF oxucu üçün fayl (format=pdf olanda).', null=True, upload_to=api.models.book_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
